config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  resources :sessions
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  resources :shifts
  resources :jobs
  resources :shift_jobs
  resources :jobs
  resources :pay_grades
  resources :pay_grade_rates


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  get 'stores/:id/payroll', to: 'payrolls#store_pay_form', as: :store_payroll
  get 'employees/:id/payroll', to: 'payrolls#emp_pay', as: :employee_payroll
  post 'payrolls', to: 'payrolls#store_calc', as: :store_calc
  get 'payrolls', to: 'payrolls#store_calc', as: :calc_store

  patch 'home/clock_in', to: 'home#clock_in', as: :clock_in
  patch 'home/clock_out', to: 'home#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions

  # Relationships
  belongs_to :store
  belongs_to :employee
  belongs_to :pay_grade
  has_many :shifts 
  
  # Scopes
  scope :current,       -> { where('end_date IS NULL') }
  scope :past,          -> { where('end_date IS NOT NULL') }
  scope :by_store,      -> { joins(:store).order('name') }
  scope :by_employee,   -> { joins(:employee).order('last_name, first_name') }
  scope :chronological, -> { order(Arel.sql('start_date DESC, end_date IS NOT NULL, end_date DESC')) }
  scope :for_store,     ->(store) { where("store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { where("employee_id = ?", employee.id) }
  scope :for_pay_grade, ->(pay_grade) { where("pay_grade_id = ?", pay_grade.id) }
  scope :for_role,      ->(role) { joins(:employee).where("role = ?", role) }
  scope :for_date,      ->(date) { where("start_date <= ? AND (end_date > ? OR end_date IS NULL)", date, date) }

  # Validations
  validates_presence_of :store_id, :employee_id, :pay_grade_id, :start_date
  validates_date :start_date, on_or_before: ->{ Date.current }, on_or_before_message: "cannot be in the future"
  validates_date :end_date, after: :start_date, on_or_before: ->{ Date.current }, allow_blank: true
  validate ->{ is_active_in_system(:employee) }
  validate ->{ is_active_in_system(:store) }
  validate ->{ is_active_in_system(:pay_grade) }  # phase 4 & 5 only

  # Other methods
  def terminate
    return false unless self.end_date.nil?
    self.start_date = Date.current
    end_previous_assignment
    remove_pending_shifts
    self.reload
  end

  # Callbacks
  before_create :end_previous_assignment

  # ... for phase 4 & 5 only
  before_destroy do
    verify_no_pending_shifts
    if errors.present?
      throw(:abort)
    else
      remove_pending_shifts
    end
  end

  private
  def end_previous_assignment
    current_assignment = Employee.find(self.employee_id).current_assignment
    if current_assignment.nil?
      return true 
    else
      current_assignment.update_attribute(:end_date, self.start_date.to_date)
    end
  end

  def verify_no_pending_shifts
    unless self.shifts.started.empty? && self.shifts.finished.empty?
      errors.add(:base, "This assignments is associated with worked shifts and cannot be deleted.")
    end
  end

  def remove_pending_shifts
    self.shifts.pending.each { |s| s.destroy }
  end
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :terminate, :destroy]
  before_action :check_login
  authorize_resource

  def index
    # for phase 3 only
    @stores = Store.active.alphabetical.to_a
    if current_user.role?(:employee)
      unless current_user.assignments.to_a.empty?
        @current_assignments = current_user.assignments.chronological.current.paginate(page: params[:page]).per_page(10)
        @past_assignments = current_user.assignments.past.chronological.paginate(page: params[:ipage]).per_page(10)
      end
    else
      if current_user.role?(:manager)
        @store = current_user.current_assignment.store
        # s_loc = @stores.index(store)
        # @stores.insert(0, @stores.delete_at(s_loc))
      else
        @store = @stores[0]
      end
      @current_assignments = Assignment.current.chronological.paginate(page: params[:page]).per_page(10)
      @past_assignments = Assignment.past.chronological.paginate(page: params[:ipage]).per_page(10)
    end

  end

  def show
    @completed_shifts = @assignment.shifts.chronological.completed.paginate(page: params[:page]).per_page(10)
    @upcoming_shifts = @assignment.shifts.chronological.incomplete
  end

  def new
    @assignment = Assignment.new
    @assignment.employee_id = params[:employee_id] unless params[:employee_id].nil?
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to assignments_path, notice: "Successfully added the assignment."
    else
      render action: 'new'
    end
  end

  def terminate
    if @assignment.terminate
      redirect_to assignments_path, notice: "Assignment for #{@assignment.employee.proper_name} terminated."
    end
  end

  def destroy
    @assignment.destroy
    redirect_to assignments_path, notice: "Removed assignment from the system."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assignment_params
    params.require(:assignment).permit(:store_id, :employee_id, :pay_grade_id, :start_date)
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment_data.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= "#{@assignment.employee.proper_name}'s Assignment" %> </h4> <br>

    <b> Store:&nbsp;&nbsp;</b>
      <%if can? :show, @assignment.store %>
        <%= link_to @assignment.store.name, store_path(@assignment.store) %>
      <%else%>
        <%=  @assignment.store.name %>
        <%end%>
      <br />
    <% if @assignment.end_date.nil? %>
      Current Assignment since <%= @assignment.start_date.strftime("%b %-d, %Y") %>
    <% else %>
    <b>Duration:&nbsp;&nbsp;</b>
      <%= @assignment.start_date.strftime("%-m/%-d/%y") %> - <%= @assignment.end_date.strftime("%-m/%-d/%y") %>
    <% end %>
    <br>
    <b>Pay Grade:&nbsp;&nbsp;</b>
      <%if can? :show, @assignment.pay_grade%> <%= link_to @assignment.pay_grade.level, pay_grade_path(@assignment.pay_grade) %>
      <%else%> <%=  @assignment.pay_grade.level %>  <%end%>
    <h4>Completed Shifts</h4>
    <table class="striped highlight">
      <thead>
        <th>Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Duration</th>
        <th>Jobs Completed</th>
        <% unless current_user.role?(:employee)%>
          <th>View Details</th>
        <% end %>
      </thead>
      <% @completed_shifts.each do |shift| %>
        <tr %>
          <td><%= shift.date.strftime("%-m/%-d/%y") %></td>
          <td><%= shift.start_time.strftime('%l:%M %p') %></td>
          <td><%= shift.end_time.strftime('%l:%M %p') %></td>
          <td><%= shift.duration%> hours</td>
          <td><%= shift.jobs.map{ |j| j.name }.join(", ") %></td>
          <% if can? :show, shift %>
            <td class = "align_center">
              <%= link_to shift_path(shift) do %>
                <i class="material-icons">details</i>
              <% end %>
            </td>
          <%end%>
        </tr>
      <% end %>
      <br>
    </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate @completed_shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
    </div>
</div>

app/views/assignments/_assignments_list.html.erb
<div class="card">
  <div class="card-content">
    <% if assignments.empty? %>
      <p>There are no <%= state.downcase %> assignments at this time.</p>
    <% else %>
    <h5><%= state.capitalize %> Assignments</h5>

      <table class="striped highlight">
        <thead>
          <th>Employee Name</th>
          <th>Store Name</th>
          <th>Pay Grade</th>
          <th>Dates</th>
          <th class = 'align_center'>View Details</th>
          <% if current_user.role?(:admin)%>
            <th>Options</th>
          <% end %>
        </thead>
        <% assignments.each do |assignment| %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td>
              <% if can? :show, assignment.employee %>
                <%= link_to assignment.employee.name, employee_path(assignment.employee) %>
              <%else%>
                <%=  assignment.employee.name%>
              <%end%>
            <td>
              <% if can? :show, assignment.store %>
                <%= link_to assignment.store.name, store_path(assignment.store) %>
              <%else%>
                <%=  assignment.store.name %>
              <%end%>
            </td>
            <td>
              <% if can? :show, assignment.pay_grade %>
                <%= link_to assignment.pay_grade.level, pay_grade_path(assignment.pay_grade) %>
              <%else%>
                <%=  assignment.pay_grade.level %>
              <%end%>
            </td>
            <td><%= assignment.start_date.strftime("%-m/%-d/%y") %> - <%= assignment.end_date.nil? ? 'Present' : assignment.end_date.strftime("%-m/%-d/%y") %></td>
            <td class = "align_center">
              <% if can? :show, assignment %>
                <%= link_to assignment_path(assignment) do %>
                  <i class="material-icons">details</i>
                <% end %>
              <% end %>
          </td>
            <% if current_user.role?(:admin)%>
              <td>
                <% if state.downcase == 'current' %>
                  <%= link_to(terminate_assignment_path(assignment), method: :patch) do %>
                    <i class="material-icons">stop</i>
                  <% end %>
                <% end %>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to(assignment_path(assignment), method: :delete, data: { confirm: 'Are you sure you wish to delete this assignment?' }) do %>
                    <i class="material-icons">delete</i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate assignments, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
    <% end %>
  </div>
</div>

app/views/assignments/_current_assignments.html.erb
<%= render partial: 'assignments_list', locals: { state: 'current', assignments: @current_assignments } %>

app/views/assignments/_fields.html.erb
<%= f.input :employee_id, collection: Employee.alphabetical.active.to_a, include_blank: true %>
<%= f.input :store_id, collection: Store.alphabetical.active.to_a, include_blank: true %>
<%= f.input :store_id, collection: Store.alphabetical.active.to_a, include_blank: true %>
<%= f.input :start_date, label_html: { class: 'active' } %>

app/views/assignments/_past_assignments.html.erb
<%= render partial: 'assignments_list', locals: { state: 'past', assignments: @past_assignments } %>

app/views/assignments/_pending_shifts.html.erb
<div class="card">
  <div class="card-content">
    <h4>Upcoming Shifts</h4>
    <% if @upcoming_shifts.empty? %>
      <p>There are no upcoming shifts at this time.</p>
    <% else %>
      <table class="striped highlight">
        <thead>
          <th>Date</th>
          <th>Start Time</th>
        </thead>
        <% @upcoming_shifts.each do |shift| %>
          <tr %>
            <td><%= shift.date.strftime("%-m/%-d/%y") %></td>
            <td><%= shift.start_time.strftime('%l:%M %p') %></td>
          </tr>
        <% end %>
        <br>
      </table>
      <p class="supertiny"></p>
      <br />
      <%end%>
    </div>
</div>

app/views/assignments/_tabbed_index.html.erb
<div id="tabbed">
  <tabs>

    <% for store in @stores %>
      <tab name="<%= store.name %>" v-bind:selected = "<%= store.name == @store.name ? 'true' : 'false'%>">
        <%= render partial: 'assignments_list', locals: { state: 'current', assignments: @current_assignments.for_store(store) } %>
        <%= render partial: 'assignments_list', locals: { state: 'past', assignments: @past_assignments.for_store(store) } %>
      </tab>

    <% end %>

  </tabs>
</div>
<p>&nbsp;</p>

app/views/assignments/index.html.erb
<%= render partial: 'partials/index_structure', locals: {model_name: 'assignment',
                                                         primary: 'tabbed_index',
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/assignments/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @assignment, 
                                                        type_of_form: 'New Assignment',
                                                        fields: 'fields'} %>

app/views/assignments/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'assignment',
                                                         object: @assignment,
                                                         primary: 'assignment_data',
                                                         secondary: nil,
                                                         sidebar: 'pending_shifts'} %>