config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  resources :sessions
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  resources :shifts
  resources :jobs
  resources :shift_jobs
  resources :jobs
  resources :pay_grades
  resources :pay_grade_rates


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  get 'stores/:id/payroll', to: 'payrolls#store_pay_form', as: :store_payroll
  get 'employees/:id/payroll', to: 'payrolls#emp_pay', as: :employee_payroll
  post 'payrolls', to: 'payrolls#store_calc', as: :store_calc
  get 'payrolls', to: 'payrolls#store_calc', as: :calc_store

  patch 'home/clock_in', to: 'home#clock_in', as: :clock_in
  patch 'home/clock_out', to: 'home#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @employee = current_user
    @store = @employee.current_assignment.store unless !logged_in? || @employee.current_assignment.nil?
    @active_stores = Store.active.alphabetical
    if !logged_in?
    elsif current_user.role == 'admin'
      @past_shifts = Shift.for_past_days(7).chronological.by_store.by_employee.paginate(page: params[:ipage]).per_page(10)
      @upcoming_shifts = Shift.for_next_days(7).chronological.by_store.by_employee.paginate(page: params[:page]).per_page(10)
    elsif current_user.role == 'manager' and !@store.nil?
      @past_shifts = Shift.for_past_days(7).for_store(@store).chronological.paginate(page: params[:ipage]).per_page(10)
      @upcoming_shifts = Shift.for_next_days(7).for_store(@store).chronological.paginate(page: params[:ipage]).per_page(10)
      @current_employees = Assignment.current.for_store(@store).map { |a| a.employee }.select{ |e| e.role =='employee' }.sort_by{|e| e.name}
    elsif  current_user.role == 'employee'
      @past_shifts = Shift.for_past_days(7).for_employee(@employee).chronological.paginate(page: params[:ipage]).per_page(10)
      @upcoming_shifts = Shift.for_next_days(7).for_employee(@employee).chronological.paginate(page: params[:page]).per_page(10)
      @shift = @upcoming_shifts.for_next_days(0).take unless @upcoming_shifts.to_a.empty?
      # @shift = TimeClock.new(shift)
    end
  end

  def clock_in
    shift = Shift.find_by(id: params[:shift_id])
    shift.update_attribute(:start_time, Time.local(2000,1,1, Time.now.hour, Time.now.min, 0))
    shift.update_attribute(:status,'started')
    #shift.save
    flash[:notice] = "clocked in at #{shift.start_time.strftime("%l:%M%p")}"
    redirect_to home_path
  end

  def clock_out
    shift = Shift.find_by(id: params[:shift_id])
    shift.update_attribute(:end_time, Time.local(2000,1,1, Time.now.hour, Time.now.min, 0))
    shift.update_attribute(:status,'finished')
    #shift.save
    flash[:notice] = "clocked out at #{shift.end_time.strftime("%l:%M%p")}"
    redirect_to home_path
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def search
    redirect_back(fallback_location: home_path) if params[:query].blank?
    @query = params[:query]
    @employees = Employee.where.not(role: 'admin').search(@query)
    @total_hits = @employees.size
  end


end

app/views/home/_admin_dashboard.html.erb
<%= render partial: 'partials/dashboard_structure' , locals: {primary: 'store_performances',
                                                         secondary: nil,
                                                         sidebar: 'active_stores'} %>

app/views/home/_current_employees.html.erb
<%= render partial: 'employee_lists', locals: { state: 'current',
                                              store: @employee.current_assignment.store.name,
                                                  employees: @current_employees } %>

app/views/home/_employee_dashboard.html.erb
<%= render partial: 'partials/dashboard_structure' , locals: {primary: 'upcoming_shifts',
                                                         secondary: 'past_shifts',
                                                         sidebar: 'employee_info'} %>

app/views/home/_employee_info.html.erb
<%= render partial: 'employees/employee_data', locals: {object: @employee} %>
<div class= "align_center">
  <%= render :partial => 'partials/display_base_errors', locals: {object: @employee} %>
    <div class="form-actions">

      <% if @employee.role == 'employee'%>
          <%= link_to employee_payroll_path(@employee), class: 'waves-effect waves-light btn' do %>
            &nbsp;View Latest Pay Report
          <% end %>
      <% end %>
      <% if can? :edit, @employee %>
        <%= link_to edit_employee_path(@employee), class: 'waves-effect waves-light btn' do %>
            &nbsp;<%= "Edit #{@employee.name}" %>
        <% end %>
      &nbsp;&nbsp;
      <% end %>
  </div>
</div>

app/views/home/_employee_lists.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Employees at
        <%= link_to store_path(@store) do %>
          <%= @store.name %> Store
      <% end %>
    </h5>
    <% if employees.empty? %>
      <p>There are no <%= state.capitalize %> at <%= store.capitalize %> Store</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Phone</th>
          <th class="align_center">Add Shift</th>
          <th>Shifts Missed this Week</th>
        </thead>
        <% for employee in employees %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td>
              <% if can? :show, employee %>
                <%= link_to employee.name, employee_path(employee) %>
              <%else%>
                <%=  employee.name %>
              <% end %>
            </td>
            <td><%= number_to_phone employee.phone %></td>
            <td class="align_center">
              <% unless current_user.role?(:employee) %>
                <%= link_to new_shift_path(assignment_id: employee.current_assignment.id) do %>
                  <i class="material-icons">add_circle</i>
                <% end %>
              <% end %>
            </td>
          <td><%= employee.shifts.for_past_days(7).pending.count %></td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    <% end %>
  </div>
</div>

app/views/home/_manager_dashboard.html.erb
<%= render partial: 'partials/dashboard_structure' , locals: {primary: 'upcoming_shifts',
                                                         secondary: 'past_shifts',
                                                         sidebar: 'current_employees'} %>

app/views/home/_past_shifts.html.erb
<%= render partial: 'shift_lists', locals: { state: 'past',
                                                  shifts: @past_shifts } %>

app/views/home/_shift_lists.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= state.capitalize %> Shifts
      <% if current_user.role?(:manager) %> at
        <strong>
          <%= link_to store_path(@store) do %>
            <%= @store.name %> Store </strong>
        <% end %>
        <% end %>
      </h5>

    <% if shifts.empty? %>
      <p>There are no <%= state.downcase %> shifts at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Employee Name</th>
          <% unless current_user.role?(:manager) %>
            <th>Store Name</th>
            <%end%>
          <th>Date</th>
          <th>Start Time</th>
          <th>End Time</th>
          <!-- <th>Status</th> -->
          <% unless current_user.role == 'employee' %>
            <th class = "align_center">Details</th>
            <th>Options</th>
            <%if state.downcase == 'past'%>
              <th>Reports Completed</th>
              <th>Edit Report</th>
            <%end%>
          <%end%>
        </thead>
        <% shifts.each do |shift| %>
          <tr %>
            <td><%= link_to shift.employee.name, employee_path(shift.employee) %></td>
            <% unless current_user.role?(:manager) %>
              <td>
                <% if can? :show, shift.store %>
                  <%= link_to shift.store.name, store_path(shift.store) %>
                <%else%>
                  <%= shift.store.name %>
                <%end%>
              </td>
            <% end %>
            <td><%= shift.date == Date.today ? 'Today' : shift.date.strftime('%b %d, %Y') %></td>
            <td><%= shift.start_time.strftime('%l:%M %p') %></td>
            <td><%= shift.end_time.nil? ? "#{shift.status.capitalize}" : shift.end_time.strftime('%l:%M %p') %></td>
            <!-- <td><%= shift.status.capitalize %> </td> -->
            <% if can? :show, shift %>
              <td class = "align_center">
                <%= link_to shift_path(shift) do %>
                  <i class="material-icons">details</i>
                <% end %>
              </td>
              <td class="align_center">
              <% if can? :manage, shift %>
                  <%= link_to edit_shift_path(shift) do %>
                    <i class="material-icons">edit</i>
                  <% end %>
                  <% if shift.status == 'pending' %>
                    <%= link_to(shift_path(shift), method: :delete, data: { confirm: 'Are you sure you wish to delete this shift?' }) do %>
                        <i class="material-icons">delete</i>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <% if state.downcase == 'past' and not current_user.role?(:employee)%>
            <td><strong><%= shift.report_completed? ? shift.shift_jobs.count : 'None'%></strong></td>

              <td class="align_center">
              <%= link_to(new_shift_job_path(shift_id: shift.id)) do %>
                  <i class="material-icons">content_paste</i>
              <% end %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
    <% end %>
  </div>
</div>

app/views/home/_store_performances.html.erb
<div class="card">
  <div class="card-content">
    <h4> Store Performances For Past Week </h4>
    <% if @active_stores.empty? %>
      <p>There are no active stores at this time.</p>
    <% else %>

      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Total Shifts Finished</th>
          <th>Number of Slacking Workers</th>
          <th>Slacking Workers</th>
        </thead>
        <% @active_stores.each do |store| %>
          <tr>
            <td><%= link_to store.name, store_path(store) %></td>
            <td><%= store.shifts.for_past_days(7).finished.count%></td>
            <td><%= store.shifts.for_past_days(7).pending.count %></td>
            <td>
              <%= store.shifts.pending.for_past_days(7).map{ |s| s.employee.proper_name}.group_by{|name| name }.sort_by{ |k, v| v.size*-1 }.map { |k,v| [" | ",k, ": ",v.size," |  "] }.take(4).join("") %>
            </td>
          </tr>
          <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    <% end %>
  </div>
</div>

app/views/home/_upcoming_shifts.html.erb
<%= render partial: 'shift_lists', locals: { state: 'upcoming',
                                                  shifts: @upcoming_shifts } %>
  <div class="form-actions", align = 'center'>
    <% if current_user.role == 'employee'%>
      <% if not @shift.nil? and @shift.status == 'pending'%>
        <%= link_to clock_in_path(shift_id: @shift.id), method: 'patch', class: 'waves-effect waves-light btn' do %>
          &nbsp;<strong>Clock in</strong>
        <% end %>
        &nbsp;&nbsp;
      <% end %>

      <% if not @shift.nil? and @shift.status == 'started'%>
        <%= link_to clock_out_path(shift_id: @shift.id), method: 'patch', class: 'waves-effect waves-light btn' do %>
            &nbsp;Clock Out
        <% end %>
        &nbsp;&nbsp;
      <% end %>
    <% end %>
  </div>

app/views/home/about.html.erb
<div class="row">
  <div class="small-7 columns">
    <h2><em>About the A &amp; M Creamery</em></h2>

    <p>
    	In 1997, when founders Mark and Alex were just little tykes, they had
      the brilliant idea of starting a joint ice cream chain where they could
      share their favorite ice creams with everyone. Not only did this build their
      brotherhood to a whole another level, it allowed them to chase their entrepreneurial dreams.
      Since then, they have been serving up cones and smiles to thousands of yinzers and they
      do not plan on stopping anytime soon.
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
</div>

app/views/home/index.html.erb
<% if logged_in? && ( current_user.role?(:admin)) %>
  <%= render :partial => "home/admin_dashboard" %>
<% elsif logged_in? && current_user.role?(:manager) %>
  <%= render :partial => "home/manager_dashboard" %>
<% elsif logged_in? && current_user.role?(:employee) %>
  <%= render :partial => "home/employee_dashboard" %>
<% else %>
  <%= render :partial => "home/general_home" %>
<% end %>

app/views/home/privacy.html.erb
<div class="row">    
  <div class="col s9">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><em>The Creamery Privacy Policy</em></span>
        <p>Our privacy policy is simple and does not require a lawyer 
          to understand it.  
          We will pounce on the opportunity to sell every
          bit of information on you we have at our disposal in order 
          to boost our bottom line.  We will gladly sell your 
          address, phone, email, age, name of pet, name of
          favorite superhero, color of bunny slippers you wear at 
          home, and the like, to any willing buyer who will pay us the big bucks.  
          (BTW, we <em>know</em> you wear bunny slippers at home and   
          we know what color they are.  You really have no secrets 
          from us.)  If you have sensitive information that you don't want us to 
          share with the world, then keep it to yourself -- don't tell us.  
          <br><br>
          It's really that simple.
        </p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<h5>Search result for term <em>'<%= @query %>'</em> resulted in <%= pluralize(@total_hits, 'hit') %></h5>
<p class="supertiny">&nbsp;</p>

<% if @employees.empty? %>
<h5>No employees matching term '<%= @query %>'</h5>
<% else %>
  <div class="card">
    <div class="card-content">
      <p><em><strong>Employees matching term '<%= @query %>'</strong></em></p>
        <table class="striped highlight">
          <thead>
            <th>Name</th>
            <th>Current Assignment</th>
            <th>Phone</th>
            <th class="align_center">Options</th>
          </thead>
          <% for employee in @employees %>
            <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
              <td>
                <% if can? :show, employee %>
                  <%= link_to employee.name, employee_path(employee) %>
                <%else%>
                  <%=  employee.name %>
                <% end %>
              </td>
              <td>
                <% if can? :show, employee.current_assignment %>
                  <%= employee.current_assignment.nil? ? 'n/a' : link_to(employee.current_assignment.store.name, assignment_path(employee.current_assignment))  %>
                <% else %>
                  <%=  employee.current_assignment.store.name %>
                <% end %>
              </td>
              <td><%= number_to_phone employee.phone %></td>
            <td class="align_center">
              <% if can? :edit, employee %>
                <%= link_to edit_employee_path(employee) do %>
                  <i class="material-icons">edit</i>
                <% end %>
              <% end %>
              <% if can? :destroy, employee %>
              <%= link_to(employee_path(employee), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
                  <i class="material-icons">delete</i>
              <% end %>
            <% end %>
            </td>
            </tr>
          <% end %>
        </table>
        <p class="supertiny"></p>
        <br />
      <% end %>
    </div>
  </div>
  <%= link_to 'Back', :back %>