config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  resources :sessions
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :employees
  resources :stores
  resources :assignments

  resources :shifts
  resources :jobs
  resources :shift_jobs
  resources :jobs
  resources :pay_grades
  resources :pay_grade_rates


  # Custom routes
  patch 'assignments/:id/terminate', to: 'assignments#terminate', as: :terminate_assignment

  get 'stores/:id/payroll', to: 'payrolls#store_pay_form', as: :store_payroll
  get 'employees/:id/payroll', to: 'payrolls#emp_pay', as: :employee_payroll
  post 'payrolls', to: 'payrolls#store_calc', as: :store_calc
  get 'payrolls', to: 'payrolls#store_calc', as: :calc_store

  patch 'home/clock_in', to: 'home#clock_in', as: :clock_in
  patch 'home/clock_out', to: 'home#clock_out', as: :clock_out

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/shift.rb
class Shift < ApplicationRecord
  include AppHelpers::Validations
  include AppHelpers::Deletions

  # Relationships
  belongs_to :assignment
  has_one :employee, through: :assignment
  has_one :store, through: :assignment
  has_many :shift_jobs #, dependent: :destroy
  has_many :jobs, through: :shift_jobs

  # Scopes
  scope :completed,     -> { joins(:shift_jobs).group(:shift_id) }
  scope :incomplete,    -> { joins("LEFT JOIN shift_jobs ON shifts.id = shift_jobs.shift_id").where('shift_jobs.job_id IS NULL') }
  # alternative ways of finding 'incomplete' scope:
  # scope :incomplete,  -> { where('id NOT IN (?)', Shift.completed.map(&:id)) }
  # also see the class method 'not_completed' further on down...
  scope :for_store,     ->(store) { joins(:assignment, :store).where("assignments.store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { joins(:assignment, :employee).where("assignments.employee_id = ?", employee.id) }
  scope :past,          -> { where('date < ?', Date.current) }
  scope :upcoming,      -> { where('date >= ?', Date.current) }
  scope :pending,       -> { where('status = ?', 'pending') }
  scope :started,       -> { where('status = ?', 'started') }
  scope :finished,      -> { where('status = ?', 'finished') }
  scope :for_next_days, ->(x) { where('date BETWEEN ? AND ?', Date.current, x.days.from_now.to_date) }
  scope :for_past_days, ->(x) { where('date BETWEEN ? AND ?', x.days.ago.to_date, 1.day.ago.to_date) }
  scope :chronological, -> { order(:date, :start_time) }
  scope :by_store,      -> { joins(:assignment, :store).order(:name) }
  scope :by_employee,   -> { joins(:assignment, :employee).order(:last_name, :first_name) }
  # scope not in phase 4 requirements (b/c uses date range object)
  scope :for_dates,     ->(date_range) { where('date BETWEEN ? AND ?', date_range.start_date, date_range.end_date) }


  # Validations
  validates_date :date, on_or_after: lambda { :assignment_starts }, on_or_after_message: "must be on or after the start of the assignment"
  validates_time :start_time #, between: [Time.local(2000,1,1,11,0,0), Time.local(2000,1,1,23,0,0)]
  validates_time :end_time, after: :start_time, allow_blank: true
  validates_inclusion_of :status, in: %w[pending started finished], message: "is not an option"
  validate :assignment_must_be_current, on: :create
  validates_presence_of :assignment_id

  # Other methods
  def report_completed?
    self.shift_jobs.count > 0
  end

  # method uses the date_time_helpers gem; https://github.com/profh/time_date_helpers
  def duration
    (round_minutes(self.end_time) - round_minutes(self.start_time, direction: :down))/3600.0
  end

  # Callbacks
  # set default end_time (on create only)
  before_create :set_shift_end_time

  # allow shifts to only be deleted if status is 'pending'
  before_destroy do
    verify_shift_is_pending
    if errors.present?
      throw(:abort)
    end
  end

  # def get_times
  #   final_times = []
  #   times = []
  #   hours = []
  #   (0..23).each do |n|
  #     hours << n.to_s
  #   end
  #   minutes = [":00",":15",":30", ":45"]
  #   for hour in hours do
  #     for min in minutes
  #       time = hour + min
  #       @times << Time.parse(time)
  #     end
  #   end
  #   return final_times
  # end





  # Misc Constants
  STATUS_LIST = [['Pending', 'pending'],['Started', 'started'],['Finished', 'finished']].freeze


  private
  def assignment_starts
    @assignment_starts = self.assignment.start_date.to_date
  end

  def assignment_must_be_current
    return true if self.assignment.nil?
    unless self.assignment.end_date.nil?
      errors.add(:assignment_id, "is not a current assignment at the creamery")
    end
  end

  def set_shift_end_time
    return true unless self.end_time.nil?
    self.end_time = self.start_time + (3*60*60)
  end

  def verify_shift_is_pending
    unless self.status == 'pending'
      errors.add(:base, "This shift either has begun or has finished and cannot be deleted.")
    end
  end



end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource


  def index
    # get data on all shifts and paginate the output to 10 per page\
    @stores = Store.active.alphabetical.to_a
    if logged_in? and current_user.role == 'employee'
      @upcoming_shifts = current_user.shifts.upcoming.chronological.paginate(page: params[:page]).per_page(10)
      @completed_shifts = current_user.shifts.completed.chronological.paginate(page: params[:ipage]).per_page(10)
    else

      if current_user.role?(:manager)
        @store = current_user.current_assignment.store
        # s_loc = @stores.index(store)
        # @stores.insert(0, @stores.delete_at(s_loc))
      else
        @store = @stores[0]
      end
      @upcoming_shifts = Shift.upcoming.chronological.paginate(page: params[:page]).per_page(10)
      @completed_shifts = Shift.completed.chronological.paginate(page: params[:ipage]).per_page(10)
    end
  end

  def show
    @jobs_completed = @shift.jobs.all.sort_by{|j| j.name}
    #@shift_jobs = ShiftJob.find(params[:shift_id])
  end

  def new
    @shift = Shift.new
    @shift.assignment_id = params[:assignment_id] unless params[:assignment_id].nil?
    get_time_options
  end

  def edit
  end

  def create
    @shift = Shift.new(shift_params)
    if @shift.save
      redirect_to home_path, notice: "Successfully added shift to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @shift.update_attributes(shift_params)
      redirect_to @shift, notice: "Updated shift information for #{@shift.name}."
    else
      render action: 'edit'
    end
  end


  def destroy
    name = @shift.employee.proper_name
    date = @shift.date.strftime('%b %d, %Y')
    @shift.destroy
    redirect_to shifts_path, notice: "Removed #{name}'s shift on #{date}"
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shift
    @shift = Shift.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shift_params
    params.require(:shift).permit(:assignment_id, :date, :start_time, :end_time, :notes, :status)
  end

  def get_time_options
    @times = []
    times = []
    times1 = []
    hours = ["12","1","2","3","4","5","6","7","8","9","10","11"]
    hours1 = []
    (0..23).each do |n|
      hours1 << n.to_s
    end
    minutes = [":00",":15",":30", ":45"]
    for hour in hours1 do
      for min in minutes
        time = hour + min
        @times << Time.parse(time)
      end
    end
    # @times = times + times
    # for time in times do
    #   @time
    # end
  end

end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_completed_shifts.html.erb
<%= render partial: 'shift_lists', locals: { state: 'completed', shifts: @completed_shifts } %>

app/views/shifts/_fields.html.erb
<%= f.input :assignment_id, collection: Assignment.current.chronological.to_a.map { |a| a.employee.name}.sort, selected: @shift.assignment_id, include_blank: true %>
<%= f.input :date, label_html: { class: 'active' }, selected: Date.today %>
<%= f.input :start_time, label_html: { class: 'active' }, collection: @times.map { |t| t.strftime('%l:%M %p') }%>
<%= f.input :end_time, label_html: { class: 'active' } %>
<%= f.input :notes, label_html: { class: 'active' } %>
<%= f.input :status, collection: ['pending', 'started', 'completed'], include_blank: true %>

app/views/shifts/_jobs_completed.html.erb
<% unless @jobs_completed.empty? %>
  <div class="card">
    <div class="card-content">
      <h5>Jobs Completed</h5>

      <table class="striped highlight">
        <thead>
          <th>Name</th>
          <th>Options</th>
          <!-- if clause -->
        </thead>
        <% @jobs_completed.each do |job| %>
          <tr %>
            <td><%= link_to job.name, job_path(job) %></td>
            <td>
            <% if can? :destroy, ShiftJob%>
              <%= link_to(shift_job_path(shift_id: @shift.id, job_id: job.id), method: :delete, data: { confirm: 'Are you sure you wish to remove this job from shift?' }) do %>
                  <i class="material-icons">delete</i>
              <% end %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
    </div>
      <div class="card-action">
        <%= link_to "Add Job to Shift", new_shift_job_path(shift_id: @shift.id) %>
      </div>

  </div>
<% else %>

  <div class="card grey lighten-3">
    <div class="card-action">
      <%= link_to "Add Job to Shift", new_shift_job_path(shift_id: @shift.id) %>
    </div>
  </div>

<% end %>

app/views/shifts/_shift_data.html.erb
<div class="card">
  <div class="card-content">
    <h4><%= @shift.employee.proper_name %></h4>
    <h5><%= @shift.employee.role.capitalize %></h5><br />

    <b>Assignment:&nbsp;&nbsp;</b><br>
      <% if @shift.assignment.nil? %>
        n/a<br /><br />
      <% else %>
        <%= link_to @shift.store.name, store_path(@shift.store) %><br />
        since <%= @shift.assignment.start_date.strftime("%b %-d, %Y") %><br /><br />
      <% end %>

    <b>Date:&nbsp;&nbsp;</b><br>
      <%= @shift.date.to_datetime.strftime("%b %-d, %Y") %><br /><br />

    <b>Start Time:&nbsp;&nbsp;</b><br>
      <%= @shift.start_time.strftime('%l:%M %p') %><br /><br />

    <b>End Time:&nbsp;&nbsp;</b><br>
      <%= @shift.end_time.nil? ? "#{shift.status.capitalize}" : @shift.end_time.strftime('%l:%M %p') %><br /><br />

    <b>Notes:&nbsp;&nbsp;</b>
      <%= @shift.notes %>
      <br>
  </div>
</div>

app/views/shifts/_shift_jobs_vue.html.erb
<div id="job_handilng">
  <%= hidden_field_tag "shift_id", @shift.id %>
  <% unless @jobs_completed.empty? %>
    <div class="card yellow lighten-4">
      <div class="card-content">
        <span class="card-title">Jobs Completed</span>
        <ul is='dosage-row'
            v-for="job in jobs"
            v-bind:job="job"
            class="no_bullet">
        </ul>
      </div>
      <% if can? :new, ShiftJob %>
        <div class="card-action">
          <!-- Could bind title based on state, but chance to show v-else directive -->
          <div v-if="modal_open">
            <%= link_to "Remove job from shift", "#", {%s(v-on:click) => "switch_modal()"} %>
          </div>
          <div v-else>
            <%= link_to "Add a new job", "#", {%s(v-on:click) => "switch_modal()"} %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <% if can? :new, ShiftJob %>
      <div class="card">
        <div class="card-action">
          <!-- Note in class that message not consistent with activity -->
          <%= link_to "Add a job to shift", "#", {%s(v-on:click) => "switch_modal()"} %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div v-if="modal_open">
    <new-job-form></new-job-form>
  </div>

</div> <!-- End of div#dosage_handling -->


<!-- Defining Vue templates to work with components -->
<script type="text/x-template" id="job-row">
  // Commenting this out b/c template in js file, but if I wanted it here...
  // <li>
  //   <a v-on:click="remove_record(dosage)" class="remove">x&nbsp;&nbsp;</a>
  //   {{ dosage.medicine_name }}:&nbsp;&nbsp;
  //   {{ dosage.units_given }}&nbsp;units
  // </li>
</script>

<!--  much easier to include this complicated template here
      rather than in the js file (IMO) -->
<script type="text/x-template" id="job-form-template">
  <%= render "shift_job_form_template", locals: {shift: @shift, job: @job, shift_job: ShiftJob.new} %>
</script>

app/views/shifts/_shift_lists.html.erb
<div class="card">
  <div class="card-content">
      <% if shifts.empty? %>
        <h5>There are no <%= state.downcase %> shifts at this time.</h5>
      <% else %>
        <h4><%= state.capitalize %> Shifts</h4>
      <table class="striped highlight">
        <thead>
          <th>Employee Name</th>
          <th>Store Name</th>
          <th>Date</th>
          <th>Start Time</th>
          <th>End Time</th>
          <!-- <th>Status</th> -->
          <th class = "align_center">View Details</th>
          <th> Options</th>
        </thead>
        <% for shift in shifts %>
          <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
            <td><%= link_to shift.employee.name, employee_path(shift.employee) %></td>
            <td><%= link_to shift.store.name, store_path(shift.store) %></td>
            <td><%= shift.date.strftime('%b %d, %Y') %></td>
            <td><%= shift.start_time.strftime('%l:%M %p') %></td>
            <td><%= shift.end_time.nil? ? "#{shift.status.capitalize}" : shift.end_time.strftime('%l:%M %p') %></td>
            <!-- <td><%= shift.status.capitalize %> </td> -->
            <td class = "align_center">
              <%= link_to shift_path(shift) do %>
                <i class="material-icons">details</i>
              <% end %>
          </td>
            <td>
              <%= link_to edit_shift_path(shift) do %>
                <i class="material-icons">edit</i>
              <% end %>

              <% if shift.status == 'pending' %>
                <%= link_to(shift_path(shift), method: :delete, data: { confirm: 'Are you sure you wish to delete this shift?' }) do %>
                    <i class="material-icons">delete</i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <p class="supertiny"></p>
      <br />
      <%= will_paginate shifts, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
      <br />
    <% end %>
  </div>
</div>

app/views/shifts/_tabbed_index.html.erb
<div id="tabbed">
  <tabs>

    <% for store in @stores %>
      <tab name="<%= store.name %>" v-bind:selected = "<%= store.name == @store.name ? 'true' : 'false'%>">
        <%= render partial: 'shift_lists', locals: { shifts: @completed_shifts.for_store(store), state: 'completed' } %>
      </tab>

    <% end %>

  </tabs>
</div>
<p>&nbsp;</p>
<div id="tabbed">
  <tabs>

    <% for store in @stores %>

      <tab name= "upcoming shifts at <%= store.name %>" v-bind:selected = "<%= store.name == @store.name ? 'true' : 'false'%>">
        <%= render partial: 'shift_lists', locals: { shifts: @upcoming_shifts.for_store(store), state: 'upcoming' } %>

      </tab>

    <% end %>

  </tabs>
</div>
<p>&nbsp;</p>

app/views/shifts/_tabbed_index2.html.erb
<div id="tabbed">
  <tabs>

    <tab name="fucker" v-bind:selected="true">
      <%= render partial: 'shift_lists', locals: { state: 'upcoming', shifts: @upcoming_shifts } %>
    </tab>
    <tab name="completed shifts" >
      nfadf

    </tab>
    <tab name="past shifts" >


    </tab>

  </tabs>
</div>

<p>&nbsp;</p>

app/views/shifts/_upcoming_shifts.html.erb
<%= render partial: 'shift_lists', locals: { state: 'upcoming', shifts: @upcoming_shifts } %>

app/views/shifts/edit.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @shift,
                                                        type_of_form: 'Shift',
                                                        fields: 'fields'} %>

app/views/shifts/index.html.erb
<%= render partial: 'partials/index_structure', locals: {model_name: 'shift',
                                                         primary: 'tabbed_index',
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/shifts/new.html.erb
<%= render partial: 'partials/form_structure', locals: {object: @shift,
                                                        type_of_form: 'New Shift',
                                                        fields: 'fields'} %>

app/views/shifts/show.html.erb
<%= render partial: 'partials/show_structure', locals: {model_name: 'shift',
                                                         object: @shift,
                                                         primary: 'shift_data',
                                                         secondary: 'secondary_information',
                                                         sidebar: 'jobs_completed'} %>